import dearpygui.dearpygui as dpg
from utils.modal import modal
from utils.profils import cfg

def init_global_shortcuts():
    with dpg.handler_registry():
        dpg.add_key_press_handler(callback=change_text)

def change_text(sender, app_data):
    if not dpg.does_item_exist("shortcuts_display"):
        modal("Key:", label="shortcuts_display", tag="shortcuts_display")
    if dpg.does_item_exist("shortcuts_displayed"):
        dpg.delete_item("shortcuts_displayed")
    txt = ""
    for key in keymap[cfg["ui"]["keyboard_map"]]:
        if dpg.is_key_down(key):
            txt += keymap[cfg["ui"]["keyboard_map"]][key] + " + "
    dpg.add_text(txt[:-3], tag="shortcuts_displayed", parent="shortcuts_display")

keymap = {
    "azerty": {
        dpg.mvKey_LControl: "Ctrl",
        dpg.mvKey_RControl: "Ctrl",
        dpg.mvKey_Control: "Ctrl",
        dpg.mvKey_Alt: "Alt",
        dpg.mvKey_LWin: "Win",
        dpg.mvKey_RWin: "Win",
        dpg.mvKey_LShift: "Shift",
        dpg.mvKey_RShift: "Shift",
        dpg.mvKey_Shift: "Shift",
        dpg.mvKey_Back: "Back",
        dpg.mvKey_Spacebar: "Spacebar",
        dpg.mvKey_Tab: "Tab",
        dpg.mvKey_Clear: "Clear",
        dpg.mvKey_Return: "Enter",
        dpg.mvKey_Pause: "Pause",
        dpg.mvKey_Capital: "Capital",
        dpg.mvKey_Escape: "Escape",
        dpg.mvKey_Prior: "Prior",
        dpg.mvKey_Next: "Next",
        dpg.mvKey_End: "End",
        dpg.mvKey_Home: "Home",
        dpg.mvKey_Left: "Left",
        dpg.mvKey_Up: "Up",
        dpg.mvKey_Right: "Right",
        dpg.mvKey_Down: "Down",
        dpg.mvKey_Select: "Select",
        dpg.mvKey_Print: "Print",
        dpg.mvKey_Execute: "Execute",
        dpg.mvKey_PrintScreen: "Print screen",
        dpg.mvKey_Insert: "Insert",
        dpg.mvKey_Delete: "Delete",
        dpg.mvKey_Help: "Help",
        dpg.mvKey_Apps: "Apps",
        dpg.mvKey_Sleep: "Sleep",
        dpg.mvKey_F1: "F1",
        dpg.mvKey_F2: "F2",
        dpg.mvKey_F3: "F3",
        dpg.mvKey_F4: "F4",
        dpg.mvKey_F5: "F5",
        dpg.mvKey_F6: "F6",
        dpg.mvKey_F7: "F7",
        dpg.mvKey_F8: "F8",
        dpg.mvKey_F9: "F9",
        dpg.mvKey_F10: "f10",
        dpg.mvKey_F11: "f11",
        dpg.mvKey_F12: "f12",
        dpg.mvKey_F13: "f13",
        dpg.mvKey_F14: "f14",
        dpg.mvKey_F15: "f15",
        dpg.mvKey_F16: "f16",
        dpg.mvKey_F17: "f17",
        dpg.mvKey_F18: "f18",
        dpg.mvKey_F19: "f19",
        dpg.mvKey_F20: "f10",
        dpg.mvKey_F21: "f11",
        dpg.mvKey_F22: "f12",
        dpg.mvKey_F23: "f13",
        dpg.mvKey_F24: "f14",
        dpg.mvKey_F25: "f15",
        dpg.mvKey_ScrollLock: "ScrollLock",
        dpg.mvKey_LMenu: "Menu",
        dpg.mvKey_RMenu: "Menu",
        dpg.mvKey_Browser_Back: "Browser back",
        dpg.mvKey_Browser_Forward: "Browser forward",
        dpg.mvKey_Browser_Refresh: "Browser refresh",
        dpg.mvKey_Browser_Stop: "Browser stop",
        dpg.mvKey_Browser_Search: "Browser search",
        dpg.mvKey_Browser_Favorites: "Browser favorites",
        dpg.mvKey_Browser_Home: "Browser home",
        dpg.mvKey_Volume_Mute: "Volume mute",
        dpg.mvKey_Volume_Down: "Volume down",
        dpg.mvKey_Volume_Up: "Volume up",
        dpg.mvKey_Media_Next_Track: "Media next track",
        dpg.mvKey_Media_Prev_Track: "Media prev track",
        dpg.mvKey_Media_Stop: "Media stop",
        dpg.mvKey_Media_Play_Pause: "Media play pause",
        dpg.mvKey_Launch_Mail: "Launch mail",
        dpg.mvKey_Launch_Media_Select: "Launch media select",
        dpg.mvKey_Launch_App1: "Launch app1",
        dpg.mvKey_Launch_App2: "Launch app2",
        dpg.mvKey_Period: "Period",
        dpg.mvKey_Multiply: "*",
        dpg.mvKey_Decimal: ",",
        dpg.mvKey_Colon: ":",
        dpg.mvKey_Plus: "+",
        dpg.mvKey_Comma: ";",
        dpg.mvKey_Minus: "-",
        dpg.mvKey_Slash: "/",
        dpg.mvKey_Tilde: "~",
        dpg.mvKey_Open_Brace: "(",
        dpg.mvKey_Close_Brace: ")",
        dpg.mvKey_Add: "+",
        dpg.mvKey_Separator: "|",
        dpg.mvKey_Subtract: "/",
        dpg.mvKey_Divide: "/",
        dpg.mvKey_Backslash: "\\",
        dpg.mvKey_Quote: "\"",
        dpg.mvKey_0: "0",
        dpg.mvKey_NumPad0: "0",
        dpg.mvKey_1: "1",
        dpg.mvKey_NumPad1: "1",
        dpg.mvKey_2: "2",
        dpg.mvKey_NumPad2: "2",
        dpg.mvKey_3: "3",
        dpg.mvKey_NumPad3: "3",
        dpg.mvKey_4: "4",
        dpg.mvKey_NumPad4: "4",
        dpg.mvKey_5: "5",
        dpg.mvKey_NumPad5: "5",
        dpg.mvKey_6: "6",
        dpg.mvKey_NumPad6: "6",
        dpg.mvKey_7: "7",
        dpg.mvKey_NumPad7: "7",
        dpg.mvKey_8: "8",
        dpg.mvKey_NumPad8: "8",
        dpg.mvKey_9: "9",
        dpg.mvKey_NumPad9: "9",
        dpg.mvKey_A: "A",
        dpg.mvKey_B: "B",
        dpg.mvKey_C: "C",
        dpg.mvKey_D: "D",
        dpg.mvKey_E: "E",
        dpg.mvKey_F: "F",
        dpg.mvKey_G: "G",
        dpg.mvKey_H: "H",
        dpg.mvKey_I: "I",
        dpg.mvKey_J: "J",
        dpg.mvKey_K: "K",
        dpg.mvKey_L: "L",
        dpg.mvKey_M: "M",
        dpg.mvKey_N: "N",
        dpg.mvKey_O: "O",
        dpg.mvKey_P: "P",
        dpg.mvKey_Q: "Q",
        dpg.mvKey_R: "R",
        dpg.mvKey_S: "S",
        dpg.mvKey_T: "T",
        dpg.mvKey_U: "U",
        dpg.mvKey_V: "V",
        dpg.mvKey_W: "W",
        dpg.mvKey_X: "X",
        dpg.mvKey_Y: "Y",
        dpg.mvKey_Z: "Z",
    },
    "qwerty": {
        dpg.mvKey_LControl: "Ctrl",
        dpg.mvKey_RControl: "Ctrl",
        dpg.mvKey_Control: "Ctrl",
        dpg.mvKey_Alt: "Alt",
        dpg.mvKey_LWin: "Win",
        dpg.mvKey_RWin: "Win",
        dpg.mvKey_LShift: "Shift",
        dpg.mvKey_RShift: "Shift",
        dpg.mvKey_Shift: "Shift",
        dpg.mvKey_Back: "Back",
        dpg.mvKey_Spacebar: "Spacebar",
        dpg.mvKey_Tab: "Tab",
        dpg.mvKey_Clear: "Clear",
        dpg.mvKey_Return: "Return",
        dpg.mvKey_Pause: "Pause",
        dpg.mvKey_Capital: "Capital",
        dpg.mvKey_Escape: "Escape",
        dpg.mvKey_Prior: "Prior",
        dpg.mvKey_Next: "Next",
        dpg.mvKey_End: "End",
        dpg.mvKey_Home: "Home",
        dpg.mvKey_Left: "Left",
        dpg.mvKey_Up: "Up",
        dpg.mvKey_Right: "Right",
        dpg.mvKey_Down: "Down",
        dpg.mvKey_Select: "Select",
        dpg.mvKey_Print: "Print",
        dpg.mvKey_Execute: "Execute",
        dpg.mvKey_PrintScreen: "Print screen",
        dpg.mvKey_Insert: "Insert",
        dpg.mvKey_Delete: "Delete",
        dpg.mvKey_Help: "Help",
        dpg.mvKey_Apps: "Apps",
        dpg.mvKey_Sleep: "Sleep",
        dpg.mvKey_F1: "F1",
        dpg.mvKey_F2: "F2",
        dpg.mvKey_F3: "F3",
        dpg.mvKey_F4: "F4",
        dpg.mvKey_F5: "F5",
        dpg.mvKey_F6: "F6",
        dpg.mvKey_F7: "F7",
        dpg.mvKey_F8: "F8",
        dpg.mvKey_F9: "F9",
        dpg.mvKey_F10: "f10",
        dpg.mvKey_F11: "f11",
        dpg.mvKey_F12: "f12",
        dpg.mvKey_F13: "f13",
        dpg.mvKey_F14: "f14",
        dpg.mvKey_F15: "f15",
        dpg.mvKey_F16: "f16",
        dpg.mvKey_F17: "f17",
        dpg.mvKey_F18: "f18",
        dpg.mvKey_F19: "f19",
        dpg.mvKey_F20: "f10",
        dpg.mvKey_F21: "f11",
        dpg.mvKey_F22: "f12",
        dpg.mvKey_F23: "f13",
        dpg.mvKey_F24: "f14",
        dpg.mvKey_F25: "f15",
        dpg.mvKey_ScrollLock: "ScrollLock",
        dpg.mvKey_LMenu: "Menu",
        dpg.mvKey_RMenu: "Menu",
        dpg.mvKey_Browser_Back: "Browser back",
        dpg.mvKey_Browser_Forward: "Browser forward",
        dpg.mvKey_Browser_Refresh: "Browser refresh",
        dpg.mvKey_Browser_Stop: "Browser stop",
        dpg.mvKey_Browser_Search: "Browser search",
        dpg.mvKey_Browser_Favorites: "Browser favorites",
        dpg.mvKey_Browser_Home: "Browser home",
        dpg.mvKey_Volume_Mute: "Volume mute",
        dpg.mvKey_Volume_Down: "Volume down",
        dpg.mvKey_Volume_Up: "Volume up",
        dpg.mvKey_Media_Next_Track: "Media next track",
        dpg.mvKey_Media_Prev_Track: "Media prev track",
        dpg.mvKey_Media_Stop: "Media stop",
        dpg.mvKey_Media_Play_Pause: "Media play pause",
        dpg.mvKey_Launch_Mail: "Launch mail",
        dpg.mvKey_Launch_Media_Select: "Launch media select",
        dpg.mvKey_Launch_App1: "Launch app1",
        dpg.mvKey_Launch_App2: "Launch app2",
        dpg.mvKey_Period: "Period",
        dpg.mvKey_Multiply: "*",
        dpg.mvKey_Decimal: ",",
        dpg.mvKey_Colon: ":",
        dpg.mvKey_Plus: "+",
        dpg.mvKey_Comma: ";",
        dpg.mvKey_Minus: "-",
        dpg.mvKey_Slash: "/",
        dpg.mvKey_Tilde: "~",
        dpg.mvKey_Open_Brace: "(",
        dpg.mvKey_Close_Brace: ")",
        dpg.mvKey_Add: "+",
        dpg.mvKey_Separator: "|",
        dpg.mvKey_Subtract: "/",
        dpg.mvKey_Divide: "/",
        dpg.mvKey_Backslash: "\\",
        dpg.mvKey_Quote: "\"",
        dpg.mvKey_0: "0",
        dpg.mvKey_NumPad0: "0",
        dpg.mvKey_1: "1",
        dpg.mvKey_NumPad1: "1",
        dpg.mvKey_2: "2",
        dpg.mvKey_NumPad2: "2",
        dpg.mvKey_3: "3",
        dpg.mvKey_NumPad3: "3",
        dpg.mvKey_4: "4",
        dpg.mvKey_NumPad4: "4",
        dpg.mvKey_5: "5",
        dpg.mvKey_NumPad5: "5",
        dpg.mvKey_6: "6",
        dpg.mvKey_NumPad6: "6",
        dpg.mvKey_7: "7",
        dpg.mvKey_NumPad7: "7",
        dpg.mvKey_8: "8",
        dpg.mvKey_NumPad8: "8",
        dpg.mvKey_9: "9",
        dpg.mvKey_NumPad9: "9",
        dpg.mvKey_A: "A",
        dpg.mvKey_B: "B",
        dpg.mvKey_C: "C",
        dpg.mvKey_D: "D",
        dpg.mvKey_E: "E",
        dpg.mvKey_F: "F",
        dpg.mvKey_G: "G",
        dpg.mvKey_H: "H",
        dpg.mvKey_I: "I",
        dpg.mvKey_J: "J",
        dpg.mvKey_K: "K",
        dpg.mvKey_L: "L",
        dpg.mvKey_M: "M",
        dpg.mvKey_N: "N",
        dpg.mvKey_O: "O",
        dpg.mvKey_P: "P",
        dpg.mvKey_Q: "Q",
        dpg.mvKey_R: "R",
        dpg.mvKey_S: "S",
        dpg.mvKey_T: "T",
        dpg.mvKey_U: "U",
        dpg.mvKey_V: "V",
        dpg.mvKey_W: "W",
        dpg.mvKey_X: "X",
        dpg.mvKey_Y: "Y",
        dpg.mvKey_Z: "Z",
    }
}